title: Stjepan Horvat / Dirty Distractions Done Dirt Cheap Entertainment / D4C Entertainment # your name (or website title) here
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Game Developer:</b>
  <br>
  - Unity
  <br>
  <br>
  
  <b>2D Artist:</b> 
  <br>
  - Photoshop
  <br>
  - Gimp
  <br>
  - Ilustrator
  <br>
  <br>
  
  <b>Feel free to contact me at:</b>
  <br>
  <a href="mailto:monster.on.hill@gmail.com">- email</a>
  <br>
  - phone:  <a href="tel:+385953530849">+385 95 353 0849</a>
  <br><br>
  
  <a href="https://www.linkedin.com/in/stjepan-horvat-92391618a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
